### ISSUE TITLE
Could not load type 'MappingGenerator.Features.CodeFixes.ExplicitConversionCodeFixProvider' 

### ISSUE THREAD

**Issue by netsharpdev** [cezarypiatek/MappingGenerator#151]
Getting this exception every time when I am opening solution.

```
System.TypeLoadException : Could not load type 'MappingGenerator.Features.CodeFixes.ExplicitConversionCodeFixProvider' from assembly 'MappingGenerator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetType(RuntimeModule module,String className,Boolean ignoreCase,Boolean throwOnError,ObjectHandleOnStack type)
   at System.Reflection.RuntimeModule.GetType(String className,Boolean throwOnError,Boolean ignoreCase)
   at Microsoft.VisualStudio.Composition.Reflection.TypeRef.get_ResolvedType()
   at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.Resolve(MethodRef methodRef)
   at Microsoft.VisualStudio.Composition.Reflection.MethodRef.Resolve()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.TryGetWorkspaceFixer(Lazy`2 lazyFixer,Workspace workspace,Boolean logExceptionWithInfoBar,CodeFixProvider& fixer)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by cezarypiatek** [comment]
Hi, 
What version of MappingGenerator and Visual Studio are you using?

**Comment by netsharpdev** [comment]
MappingGenerator: 1.20.463 and VS: 16.8.2
also using Resharper if it matters. - 2020.2.4

**Comment by cezarypiatek** [comment]
I'm not able to reproduce the problem and it looks more like a VS bug. According to the error message there's a problem with `'MappingGenerator, Version=1.0.0.0,` - I checked the published VSIX package (as well as recent nuget packages) and it contains assembly with correct version attribute `1.20.463`. What distribution of MappingGenerator are you using? VSExtension or nuget package?  If it's a VSIX then please uninstall the extension, clean up the temp dir and install it again. Please let me know if that helped.

**Comment by jzabroski** [comment]
@netsharpdev Is it possible you have both the nuget package and VSIX extension installed?

@cezarypiatek What happens when that occurs, anyway?  Say I Install the VSIX extension 1.20.463 and a coworker checks in a change with `<PackageReference Include="MappingGenerator" Version="Some.Other.Version" />`, and I take latest and run restore packages.  What happens?

**Comment by jzabroski** [comment]
I wonder if the MappingGenerator VSIX extension should actually be a MappingGenerator.Locator that, on load, first checks the solution for nuget packages, and instead of providing a Generate mapping code hint, instead providesa "Install MappingGenerator package" hint.

Does that make sense?  It's probably way cleaner because people tend to update nuget packages more often than VSIX extensions in my experience.

**Comment by netsharpdev** [comment]
@cezarypiatek I had VSIX but repeated your steps and still have the same. 
@jzabroski I had no nuget package installed together with VSIX.

Currently, I removed VSIX and installed nuget and it seems to work perfectly fine.

**Comment by cezarypiatek** [comment]
Hi @jzabroski 
The preferred way to "consume" MappingGenerator is VSIX when you are the VS user. The nuget package is intended only for JetBrains Rider IDE user. MappingGenerator is created using CodeRefactoring API. Visual Studio is not supporting code refactoring's distributed as nuget packages - only analyzers and code fixes are supported. On the other hand, Rider doesn't support VSIX but it's able to load code refactorings from the nuget.

**Comment by netsharpdev** [comment]
@cezarypiatek I think i have found an issue. Somehow I had installed two "MappingGenerators" one with 1.9.269 version and another with 1.20.468. I uninstalled the old version and installed once again the latest one and it is fine. I am closing an issue.
![mappinggenerator](https://user-images.githubusercontent.com/25545756/102722906-a01b3580-4304-11eb-88a8-c893d5beef17.png)

This screenshot has been taken at the same time when the previous one.
![mappinggen2](https://user-images.githubusercontent.com/25545756/102722908-a0b3cc00-4304-11eb-8a78-c066d1373742.png)

**Comment by cezarypiatek** [comment]
@netsharpdev  thanks for letting me know.  Probably 1.9.269 version has invalid package id - this issue was fixed in the past.

**Comment by jzabroski** [comment]
> Visual Studio is not supporting code refactoring's distributed as nuget packages - only analyzers and code fixes are supported.

Got it.  I did not understand there was a difference between "code refactoring" and "code fix."  Seems rather baroque but Visual Studio tends to have baroque policies.

**Comment by cezarypiatek** [comment]
Code fixes are a kind of "refactoring" that are suggested for reported diagnostic. The code refactorings are not connected with the diagnostics. That's the main difference. There's also a difference how VS is handling those two types of roslyn extensions, which I described in my latest comment about that.

**Comment by jzabroski** [comment]
Thank you.  I'm still a newbie and trying to write my first set of analyzers/code fixes, so your explanation helps correct some knowledge gaps.  Very appreciated.
