### ISSUE TITLE
Error when opening quick actions menu

### ISSUE THREAD

**Issue by cocowalla** [cezarypiatek/MappingGenerator#57]
I've just installed this extension, but get an error when opening the Visual Studio "Quick Actions" menu, before I've even hit "Generate mapping code". Stack trace:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.<>c.<.ctor>b__10_0(SyntaxNode n)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection,IEqualityComparer`1 comparer)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1..ctor(IEnumerable`1 nodes,Func`3 computeReplacementNode,IEnumerable`1 tokens,Func`3 computeReplacementToken,IEnumerable`1 trivia,Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replace[TNode](SyntaxNode root,IEnumerable`1 nodes,Func`3 computeReplacementNode,IEnumerable`1 tokens,Func`3 computeReplacementToken,IEnumerable`1 trivia,Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes,Func`3 computeReplacementNode,IEnumerable`1 tokens,Func`3 computeReplacementToken,IEnumerable`1 trivia,Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.ReplaceNode[TRoot](TRoot root,SyntaxNode oldNode,SyntaxNode newNode)
   at async MappingGenerator.SyntaxGeneratorExtensions.ReplaceNodes(<Unknown Parameters>)
   at async MappingGenerator.MappingGeneratorRefactoring.GenerateMappingMethodBody(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

I'm on Visual Studio 2017, version 15.9.4.

Before opening the Quick Actions menu, I've typed this stub:

```
public static class Mapper
{
    public static MyDTO Map(MyEntity entity)
}
```

**Comment by cezarypiatek** [comment]
Hi

Could you provide your code of `MyDTO` and `MyEntity` classes?

**Comment by cocowalla** [comment]
Sorry, I had meant to mention, the issue is present even with the most trivial classes:

```
public class Test
{
    public static class Mapper
    {
        public static Dto Map(Entity entity)
    }
}

public class Entity
{
    public Guid? Id { get; set; }
}

public class Dto
{
    public Guid? Id { get; set; }
}
```

But! I just noticed that the issue only presents if I have a stub _without parentheses_. So, this causes the error:

`public static Dto Map(Entity entity)`

Whereas it does work if I add the brackets first:

```
public static Dto Map(Entity entity)
{

}
```

**Comment by cezarypiatek** [comment]
@cocowalla
Here's a version with fixed issue. Would you mind to test it and tell me if everything is working as expected?
https://ci.appveyor.com/api/buildjobs/4o5lo4e0ga2a7uy1/artifacts/MappingGenerator%2FMappingGenerator%2FMappingGenerator.Vsix%2Fbin%2FRelease%2FMappingGenerator.vsix

**Comment by cocowalla** [comment]
@cezarypiatek excellent, it works as expected 😄

**Comment by cezarypiatek** [comment]
Thanks for testing.
