### ISSUE TITLE
Exception when generating mapping

### ISSUE THREAD

**Issue by zpqrtbnk** [cezarypiatek/MappingGenerator#75]
I create this code:
~~~~
public Thing1 Test(Thing2 thing)
{
}
~~~~
Where `Thing1` and `Thing2` have some properties in common, and other, non-common properties. Oh and they might also have properties matching by name but not by type. And maybe `Thing1` has only parameter-less constructors.

Gettings this exception soon as I hit the generate menu:
~~~~
System.NullReferenceException : Object reference not set to an instance of an object.
   at MappingGenerator.MappingEngine.<>c__DisplayClass9_2.<TryToCreateMappingExpression>b__3(MappingElement x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source,Func`2 predicate)
   at MappingGenerator.MappingEngine.<>c__DisplayClass9_1.<TryToCreateMappingExpression>b__2(MappingElement foundElement)
   at MappingGenerator.IgnorableMappingSourceFinder.FindMappingSource(String targetName,ITypeSymbol targetType)
   at MappingGenerator.MappingEngine.<>c__DisplayClass11_0.<MapUsingSimpleAssignment>b__0(IPropertySymbol property)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MappingGenerator.MappingEngine.MapUsingSimpleAssignment(SyntaxGenerator generator,IEnumerable`1 targets,IMappingSourceFinder sourceFinder,MappingPath mappingPath,SyntaxNode globalTargetAccessor)
   at MappingGenerator.MappingEngine.AddInitializerWithMapping(ObjectCreationExpressionSyntax objectCreationExpression,IMappingSourceFinder mappingSourceFinder,ITypeSymbol createdObjectTyp,MappingPath mappingPath)
   at MappingGenerator.MappingEngine.TryToCreateMappingExpression(MappingElement source,ITypeSymbol targetType,MappingPath mappingPath)
   at MappingGenerator.MappingEngine.MapExpression(MappingElement element,ITypeSymbol targetType,MappingPath mappingPath)
   at MappingGenerator.MappingEngine.MapExpression(ExpressionSyntax sourceExpression,ITypeSymbol sourceType,ITypeSymbol destinationType)
   at MappingGenerator.MappingGeneratorRefactoring.GenerateMappingCode(IMethodSymbol methodSymbol,SyntaxGenerator generator,SemanticModel semanticModel)
   at async MappingGenerator.MappingGeneratorRefactoring.GenerateMappingMethodBody(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
~~~~

Is it... that I am doing something that I should not do, or is it some kind of anomaly?

**Comment by cezarypiatek** [comment]
Hi

Could you provide definitions of `Thing1` and `Thing2` classes?

**Comment by zpqrtbnk** [comment]
Tried to do my homework, using the unit tests in the MappingGenerator project. Been able to narrow it down to
~~~~
    public class Thing1
    {
        public string Value { get; set; }
    }

    public class Thing2
    {
        public Thing2(string value)
        { }

        public string Value { get; set; }
    }
~~~~

The non-empty ctor is killing it. Which... kinda makes sense I assume?

**Comment by cezarypiatek** [comment]
I guess this could be related to the new feature #64 I will take a look at this on the next weekend. Thanks for due diligence.

**Comment by zpqrtbnk** [comment]
Cool. No rush, enjoy your weekend ;-)

**Comment by cezarypiatek** [comment]
I was't able to reproduce this issue using your example. Here's the proof

![issue75](https://user-images.githubusercontent.com/7759991/54866957-4d04ff00-4d7b-11e9-954d-0f1f8d550e66.gif)

Can you create a fork with UT that is reproducing the problem?

**Comment by cezarypiatek** [comment]
Still no luck with reproducing, but probably I've found the culprit. Here's version with the fix https://ci.appveyor.com/api/buildjobs/24v6iq24h1bxu8rx/artifacts/MappingGenerator%2FMappingGenerator%2FMappingGenerator.Vsix%2Fbin%2FRelease%2FMappingGenerator.vsix

@zpqrtbnk would you mind to install it and verify if everything is working as expected?

**Comment by zpqrtbnk** [comment]
Arh - got side tracked on other stuff, will try soon as I can

**Comment by cezarypiatek** [comment]
Thanks @brrbtr  for testing.

**Comment by cezarypiatek** [comment]
An official version with this fix was released Please install version of the official channel https://marketplace.visualstudio.com/items?itemName=54748ff9-45fc-43c2-8ec5-cf7912bc3b84.mappinggenerator
